export default {
  icLoadingGrey: require('./loadingGrey.gif'),
  logo: require('./logo.jpg'),
  carousel_1: require('./carousel-1.png'),
  carousel_2: require('./carousel-2.jpg'),
  carousel_3: require('./carousel-3.png'),
  shipping: require('./shipping.png'),
  car: require('./car.png'),
  heart: require('./heart.png'),
  money: require('./money.png'),
  star: require('./star.png'),
  gift: require('./gift.png'),
  spin: require('./spin.png'),
  bookmark: require('./bookmark.png'),
  bds: require('./discover_bds.jpg'),
  dt: require('./discover_dt.jpg'),
  dogiadung: require('./discover_dogiadung.jpg'),
  me: require('./discover_me.jpg'),
  xe: require('./discover_xe.jpg'),
  giaitri: require('./discover_giaitri.jpg'),
  job: require('./discover_job.png'),
  dulich: require('./discover_dulich.jpeg'),
};
